version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          USER_ID: ${UID:-1000}
          GROUP_ID: ${GID:-1000}
    env_file: .env
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel_net

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - laravel_net

  db:
    image: postgres:17-alpine
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: laravel_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge

volumes:
  pgdata:
  rabbitmq_data:
